CREATE TABLE IF NOT EXISTS broadcasts (
    id VARCHAR(255) PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    senderId VARCHAR(255),
    targetId VARCHAR(255),
    targetType ENUM('ALL', 'OFFICIALS_ONLY', 'INDIVIDUALS', 'JURISDICTION_MEMBERS') DEFAULT 'JURISDICTION_MEMBERS',
    targetOfficialLevel ENUM('NATIONAL', 'STATE', 'LOCAL_GOVERNMENT', 'BRANCH'),
    createdAt TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP(3),
    updatedAt TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)
);

CREATE TABLE IF NOT EXISTS broadcast_recipients (
    id VARCHAR(255) PRIMARY KEY,
    broadcastId VARCHAR(255) NOT NULL,
    userId VARCHAR(255) NOT NULL,
    status ENUM('DELIVERED', 'READ') DEFAULT 'DELIVERED',
    deliveredAt TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP(3),
    readAt TIMESTAMP(3)
);

CREATE TABLE IF NOT EXISTS backups (
    id VARCHAR(255) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    type ENUM('MANUAL', 'AUTOMATED') DEFAULT 'MANUAL',
    databaseUrl VARCHAR(500),
    filesUrl VARCHAR(500),
    size BIGINT,
    status ENUM('PENDING', 'COMPLETED', 'FAILED') DEFAULT 'PENDING',
    error TEXT,
    createdAt TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP(3),
    createdBy VARCHAR(255)
);
