import {
  Home, LayoutDashboard, Radio, MessageSquare, Banknote, Megaphone, BarChart3, Box,
  Calendar, FileText, Library, Users, Newspaper, Image, MapPin, Building2, Handshake,
  Award, Trophy, CreditCard, Scroll, Shield, Briefcase, UserCheck, Settings, Database,
  Heart, BookOpen, StickyNote, ClipboardList, KeyRound, Wallet,
} from "lucide-react";

export interface GuideModule {
  id: string;
  title: string;
  icon: any;
  color: string;
  audience: string;
  summary: string;
  sections: { heading: string; body: string }[];
}

export const GUIDES: GuideModule[] = [
  {
    id: "getting-started",
    title: "Getting Started",
    icon: Home,
    color: "bg-emerald-600",
    audience: "Everyone",
    summary: "Log in, choose your view, and navigate the portal.",
    sections: [
      { heading: "Signing in", body: "Go to Login, enter your email + password. New members sign up and verify their email first. You must verify your email before your first sign-in." },
      { heading: "Your role decides your view", body: "The portal shows different menus based on your role — Member, Official, or Admin. Use the 'View As' buttons (bottom-left) on a National Admin account to preview the Member, Branch, LGA, or State experience." },
      { heading: "The dashboard", body: "Your home screen summarises what matters for your role: your programmes, meetings, payments, notifications, and quick links." },
      { heading: "Notifications & messages", body: "The bell (top-right) shows in-app notifications (programme reminders, event alerts). Messages is your private 1-to-1 and group chat." },
    ],
  },
  {
    id: "profile-account",
    title: "Profile & Account",
    icon: Users,
    color: "bg-blue-600",
    audience: "Everyone",
    summary: "Manage your details, password, and security keys.",
    sections: [
      { heading: "My Profile", body: "Update your name, phone, address, and photo. Your membership details auto-link to events you register for." },
      { heading: "Password & email", body: "Use Forgot Password to reset via email. Keep your email verified to avoid login issues." },
      { heading: "Encryption keys (chat)", body: "If you use end-to-end encrypted chat, set up your security keys once. Keep your recovery key safe — it restores access to your encrypted messages." },
    ],
  },
  {
    id: "members",
    title: "Members",
    icon: Users,
    color: "bg-green-700",
    audience: "Admins / Officials",
    summary: "Register, approve and manage members at your jurisdiction.",
    sections: [
      { heading: "Member workflow", body: "Members register and are reviewed through a chain: PENDING → RECOMMENDED → ACTIVE. A recommender and an approver (at the right level) each sign off." },
      { heading: "Manage members", body: "Search members, view profiles, change status (activate, suspend, expire), and see their payments and documents." },
      { heading: "Membership IDs", body: "Each member gets an auto-generated TMC membership ID from the jurisdiction code + a running serial." },
    ],
  },
  {
    id: "officials",
    title: "Officials",
    icon: UserCheck,
    color: "bg-teal-600",
    audience: "Admins",
    summary: "Appoint officials and assign offices.",
    sections: [
      { heading: "Appointing officials", body: "Create an official record per position (President, Secretary, Treasurer…), set the level (Branch/LGA/State/National), and link them to an office and term dates." },
      { heading: "Offices", body: "Set up departmental offices (Dawah, Education, Finance, Welfare…). Each office reports its activities monthly." },
    ],
  },
  {
    id: "organizations",
    title: "Organizations & Jurisdictions",
    icon: Building2,
    color: "bg-indigo-600",
    audience: "National Admin",
    summary: "Build the National → State → LGA → Branch hierarchy.",
    sections: [
      { heading: "The hierarchy", body: "Create State, LGA and Branch records under their parent. Each has a code, city, state, and contact info. Access is inherited top-down." },
      { heading: "Planning settings", body: "Set a planning deadline month/day per organisation and the year-planner window (see Settings)." },
      { heading: "Payments", body: "Each organisation can have its own Paystack subaccount, so fees route to the right account. Add bank details here." },
    ],
  },
  {
    id: "programmes",
    title: "Programmes & Events",
    icon: Calendar,
    color: "bg-emerald-700",
    audience: "Everyone",
    summary: "Plan, approve, register, attend, report and certificate events.",
    sections: [
      { heading: "Lifecycle", body: "Plan → Submit → State approval → National approval → APPROVED → register → attend → report → COMPLETED. Statuses: DRAFT, PENDING_STATE, PENDING_NATIONAL, APPROVED, REJECTED, CANCELLED, POSTPONED, COMPLETED." },
      { heading: "Create a programme", body: "Title, description, venue, dates, audience, level, format (Physical/Virtual/Hybrid), budget, committee, office/official. Tick 'repetitive/administrative' to auto-approve recurring events." },
      { heading: "Fees & early-bird", body: "Set a fee and optionally an Early-Bird price + deadline. Anyone registering before the deadline pays the lower price, locked even if the fee later rises." },
      { heading: "Registration & payment", body: "Members register from the event page; pay via Paystack (card/transfer) or Wallet. Installments allowed if enabled. You get an access slip with a QR code." },
      { heading: "Attendance", body: "Record via self scan (QR), a gatekeeper, the kiosk, or a camera QR scanner. Attendance only within the window (default 3h before start). Virtual/Hybrid join auto-marks attendance." },
      { heading: "Reports & grading", body: "After the event, submit a report (summary, attendees, spend, lecturers) which marks it COMPLETED and feeds the cumulative reports and grading." },
      { heading: "Certificates", body: "Paid, attended participants can download a certificate (PDF with the TMC logo). Admins can send certificates to all/selected attendees." },
      { heading: "Lounge & notes", body: "Each event has a group chat (Lounge) and a OneNote-style notebook (Notes)." },
    ],
  },
  {
    id: "programme-reports",
    title: "Programme Reports & Grading",
    icon: BarChart3,
    color: "bg-cyan-600",
    audience: "Admins",
    summary: "Cumulative reports, analytics and performance grading.",
    sections: [
      { heading: "Cumulative reports", body: "Filter by monthly/quarterly/annual/YTD, year, quarter, month, office and jurisdiction. See totals (programmes, attendees, spend, budget), charts by period/office/level, and a detailed table." },
      { heading: "Export & share", body: "Download a report as CSV or PDF, or copy a shareable link for the same filtered view." },
      { heading: "Grading", body: "Each programme/department is graded on 5 weighted factors — completion, punctuality, attendance, budget discipline, quality — into a score (0–100) and a letter grade (A–F)." },
      { heading: "Jurisdiction scope", body: "Branch admins see Branch only; State sees State + LGA + Branch; National sees everything." },
    ],
  },
  {
    id: "meetings",
    title: "Meetings",
    icon: Users,
    color: "bg-purple-600",
    audience: "Everyone",
    summary: "Schedule meetings, groups and live video rooms.",
    sections: [
      { heading: "Create a meeting", body: "Title, description, org, date/time, venue, online link. Mark it online (Virtual/Hybrid) to get a LiveKit video room. Set a meeting group and target audience." },
      { heading: "Meeting groups", body: "Create groups (e.g. State Executives) and add members so invitations are targeted." },
      { heading: "Live video room", body: "Join via the room link. The coordinator starts the session; attendees can publish video/audio. Recording can be started to save to cloud." },
      { heading: "Attendance & minutes", body: "Everyone is marked PRESENT on join. Upload agenda, minutes and member reports. Track submissions as on-time/late." },
      { heading: "Notes", body: "Each meeting has a OneNote-style notebook — take notes before (Agenda), during (Minutes), and after (Actions). Auto-saves and can be shared." },
    ],
  },
  {
    id: "finance",
    title: "Finance & Donations",
    icon: Banknote,
    color: "bg-amber-600",
    audience: "Admins / Members",
    summary: "Budgets, fund requests, transactions, fees and donations.",
    sections: [
      { heading: "Budgets", body: "Create annual budgets with line items and an approval flow (Draft → Submitted → Approved)." },
      { heading: "Fund requests", body: "Request funds with a recommendation → approval → disbursement chain. Link evidence and receipts." },
      { heading: "Transactions", body: "Record inflows and outflows; each payment and fee is tracked as a transaction with a category." },
      { heading: "Fees & levies", body: "Set fees (member dues, levies) targeted at all members or officials, with due dates and per-member assignments." },
      { heading: "Fundraising campaigns", body: "Create donation campaigns with a target, suggested amounts, and a progress tracker. Donations flow through payments." },
      { heading: "Wallet", body: "Members can keep a wallet balance and pay for programmes/events from it." },
    ],
  },
  {
    id: "payments",
    title: "Payments & Paystack",
    icon: CreditCard,
    color: "bg-green-600",
    audience: "Everyone",
    summary: "All money in: membership, fees, events, donations, burial.",
    sections: [
      { heading: "Types", body: "Membership fee, renewal, donation, event fee, burial fee, levy, contest fee." },
      { heading: "How payment works", body: "Payments go through Paystack (card/transfer) or the in-app Wallet. A verification step confirms the transaction and updates the record." },
      { heading: "Receipts", body: "Once verified you get a receipt and, for events, an access slip. Organisations can route funds to their own Paystack subaccount." },
    ],
  },
  {
    id: "documents",
    title: "Documents",
    icon: FileText,
    color: "bg-slate-600",
    audience: "Everyone",
    summary: "Upload, store and share files securely.",
    sections: [
      { heading: "Upload & organise", body: "Upload documents (ID cards, certificates, reports, minutes). Tag a type, description and whether it's public. Files are stored in cloud storage." },
      { heading: "Access", body: "Members see their own documents; officials/admins see jurisdiction-scoped files. Public documents are visible on the site." },
    ],
  },
  {
    id: "broadcasts",
    title: "Broadcasts",
    icon: Radio,
    color: "bg-rose-600",
    audience: "Admins / Officials",
    summary: "Send announcements to targeted audiences.",
    sections: [
      { heading: "Create a broadcast", body: "Title + content with optional media. Choose the target: everyone, officials only, individuals, or members of a specific jurisdiction/level." },
      { heading: "Delivery tracking", body: "Recipients are recorded and marked DELIVERED, then READ when they open it." },
    ],
  },
  {
    id: "messages",
    title: "Messages & Chat",
    icon: MessageSquare,
    color: "bg-sky-600",
    audience: "Everyone",
    summary: "1-to-1 and group chat with optional encryption.",
    sections: [
      { heading: "Chats", body: "Start a direct message or a group. Create groups for any purpose; admins can moderate." },
      { heading: "Encryption", body: "You can send end-to-end encrypted messages. Set up your key once; protect your recovery key." },
      { heading: "Media", body: "Send images and attachments alongside text." },
    ],
  },
  {
    id: "notes",
    title: "Meeting Notes (OneNote)",
    icon: StickyNote,
    color: "bg-fuchsia-600",
    audience: "Everyone",
    summary: "A OneNote-style notebook for meetings and events.",
    sections: [
      { heading: "Sections", body: "Pages are grouped into General, Agenda, Minutes, Decisions, Actions, and Follow-up — pick a section on the left, then create pages." },
      { heading: "Editing", body: "The rich editor auto-saves every keystroke (800ms). Paste images, add checklists (- [ ]), and format freely." },
      { heading: "Share & export", body: "Toggle Share to make a page visible to attendees; export any page to PDF." },
    ],
  },
  {
    id: "assets",
    title: "Assets",
    icon: Box,
    color: "bg-lime-600",
    audience: "Admins",
    summary: "Track equipment, furniture and their maintenance.",
    sections: [
      { heading: "Register an asset", body: "Name, category, serial number, condition, status, purchase price/date, current value, location and custodian." },
      { heading: "Maintenance", body: "Log repairs/services with cost, date and next service date so nothing is forgotten." },
    ],
  },
  {
    id: "news",
    title: "News, Posts & Content (CMS)",
    icon: Newspaper,
    color: "bg-orange-600",
    audience: "Admins",
    summary: "Publish posts, pages, menus and galleries.",
    sections: [
      { heading: "Posts", body: "Write news, events and announcements (rich text + cover image + excerpt). Publish to make them live." },
      { heading: "Pages & menus", body: "Create organisation-scoped pages (slug, content, SEO metadata) and arrange the site navigation/menus." },
      { heading: "Galleries", body: "Upload image galleries with captions to display photos on the site." },
    ],
  },
  {
    id: "adhkar",
    title: "Adhkar & Teskiyah Centres",
    icon: MapPin,
    color: "bg-teal-700",
    audience: "Admins",
    summary: "Manage the directory of prayer and learning centres.",
    sections: [
      { heading: "Centres", body: "Add name, venue, address, meeting time, state/LGA and contact. These appear in the public Adhkar/Teskiyah directories." },
    ],
  },
  {
    id: "organs",
    title: "Organs & TMC Programmes",
    icon: Building2,
    color: "bg-violet-600",
    audience: "Admins",
    summary: "Institutional bodies and evergreen programmes.",
    sections: [
      { heading: "Organs", body: "List the congress organs/subsidiaries with descriptions, websites and logos for the public page." },
      { heading: "TMC programmes", body: "Define evergreen programme categories shown on the 'Our Programmes' page." },
    ],
  },
  {
    id: "occasions",
    title: "Engagements & Occasions",
    icon: Handshake,
    color: "bg-pink-600",
    audience: "Members / Admins",
    summary: "Request coordination for engagements (nikkah, naming, etc.).",
    sections: [
      { heading: "Occasion types", body: "Admins define occasion types (e.g. Nikkah, Naming) with an optional certificate fee." },
      { heading: "Request an occasion", body: "Submit a request with the date, venue, your role, and whether you need a certificate. Pay any fee, then it's approved." },
    ],
  },
  {
    id: "competitions",
    title: "Competitions (Forms & Applications)",
    icon: Award,
    color: "bg-amber-700",
    audience: "Admins",
    summary: "Create questionnaires, applications and contest forms.",
    sections: [
      { heading: "Build a form", body: "Add fields (text, email, number, date, select, textarea) with labels and required flags. Great for applications and registrations like a spelling bee." },
      { heading: "Collect responses", body: "Publish it, collect submissions, search/filter, and export to CSV. Mark submissions as reviewed/approved." },
    ],
  },
  {
    id: "contests",
    title: "Contests Live (Quran/Debate/Written)",
    icon: Trophy,
    color: "bg-emerald-600",
    audience: "Admins / Officials",
    summary: "Run live multi-phase competitions with real-time judging.",
    sections: [
      { heading: "Create & open", body: "Create a contest (category, level, format, optional fee/early-bird). Open it to let jurisdictions submit representatives." },
      { heading: "Run the event", body: "Generate the timetable → call participants → they perform in a video room → judges grade on a score card → compute results → the top are promoted to the next phase (Branch → LGA → State → National)." },
      { heading: "Written contests", body: "For written categories, contestants answer in a timed editor that auto-submits when time is up." },
      { heading: "Full guide", body: "See the dedicated 'Contest Guide' link in the sidebar for the step-by-step admin walkthrough." },
    ],
  },
  {
    id: "burials",
    title: "Burials",
    icon: Scroll,
    color: "bg-gray-600",
    audience: "Members / Admins",
    summary: "Request burial support and receive a certificate.",
    sections: [
      { heading: "Submit a request", body: "Enter the deceased's details, your relationship, cause and place of death, and contact info." },
      { heading: "Approval & payment", body: "An admin approves it, then the standard fee is paid (via Paystack) before a burial certificate is issued." },
    ],
  },
  {
    id: "promotions",
    title: "Promotions & Adverts",
    icon: Megaphone,
    color: "bg-indigo-500",
    audience: "Members / Admins",
    summary: "Buy advertising space on the portal.",
    sections: [
      { heading: "Plans", body: "Admins define promotional plans (duration + price)." },
      { heading: "Run an ad", body: "Members choose a plan, upload their advert (image + link), pay, and it goes live once approved." },
    ],
  },
  {
    id: "constitution",
    title: "Constitution",
    icon: BookOpen,
    color: "bg-blue-700",
    audience: "Members / Officials",
    summary: "Review and amend the constitution in phases.",
    sections: [
      { heading: "Read", body: "View the live constitution on the public site." },
      { heading: "Review rounds", body: "During a review window, members and collation levels (LGA/State/National) submit feedback section-by-section." },
      { heading: "Workspace", body: "Admins manage reviewers, feedback, and collation analytics in the Constitution Workspace." },
    ],
  },
  {
    id: "reports",
    title: "Activity Reports (Monthly/Quarterly/Annual)",
    icon: FileText,
    color: "bg-cyan-700",
    audience: "Admins / Officials",
    summary: "Offices report their activities upward; executives review.",
    sections: [
      { heading: "Monthly office report", body: "Each office submits a monthly activity report (summary, achievements, challenges, attachment) to executives at its jurisdiction." },
      { heading: "Quarterly & annual", body: "Admins auto-generate a quarterly/annual rollup for an individual office or the national office from the monthly reports. Approve or reject pending ones." },
      { heading: "Generate", body: "Use the 'Generate Quarterly & Annual' panel on the Activity Reports page, previewing coverage before creating." },
    ],
  },
  {
    id: "audit",
    title: "Audit Logs",
    icon: Shield,
    color: "bg-gray-700",
    audience: "National Admin",
    summary: "See a complete trail of who did what.",
    sections: [
      { heading: "What's logged", body: "Every create/update/delete across modules records the user, action, entity, and metadata with IP and timestamp." },
    ],
  },
  {
    id: "roles",
    title: "Roles & Permissions (RBAC)",
    icon: Briefcase,
    color: "bg-emerald-800",
    audience: "Admins",
    summary: "Define roles and granular permissions.",
    sections: [
      { heading: "Roles", body: "Create roles (Super Admin, National/State/LGA/Branch Admin, Official, Member) each with a jurisdiction level." },
      { heading: "Permissions", body: "Grant each role fine-grained permissions (members, officials, payments, documents, reports, etc.)." },
      { heading: "Assign to users", body: "Assign roles to users at a specific organisation; roles can expire." },
    ],
  },
  {
    id: "users",
    title: "Users & Access",
    icon: UserCheck,
    color: "bg-slate-700",
    audience: "Admin",
    summary: "Manage accounts, roles and impersonation.",
    sections: [
      { heading: "User accounts", body: "Search users, view their roles/membership/officialships, and assign or remove roles." },
      { heading: "Impersonate", body: "A Super Admin can temporarily 'view as' another user to troubleshoot, then revert." },
    ],
  },
  {
    id: "settings",
    title: "Settings",
    icon: Settings,
    color: "bg-blue-700",
    audience: "Admin / National Admin",
    summary: "Configure the portal's core options.",
    sections: [
      { heading: "Year planner", body: "Set the active year, open the next year's submissions, allow past activities, and set the archive start year." },
      { heading: "Integrations", body: "Configure LiveKit (video), S3/Wasabi storage, and AI providers (Gemini/DeepSeek)." },
      { heading: "AI assistant", body: "Enable the in-app AI chat and choose which provider powers it." },
      { heading: "Emails & templates", body: "Manage email templates and Resend settings for notifications." },
      { heading: "Financial", body: "Set values like the burial verification fee." },
    ],
  },
  {
    id: "backups",
    title: "Backups",
    icon: Database,
    color: "bg-emerald-900",
    audience: "Admin / National Admin",
    summary: "Back up the database and files.",
    sections: [
      { heading: "Backups", body: "Create manual backups and schedule automated ones (database + files) to cloud storage. Track status and size, and restore if needed." },
    ],
  },
  {
    id: "analytics",
    title: "Site & Finance Analytics",
    icon: BarChart3,
    color: "bg-violet-700",
    audience: "Admins",
    summary: "SEO/visitor analytics and financial dashboards.",
    sections: [
      { heading: "Site analytics", body: "Track visits, unique visitors, and popular pages to understand your audience." },
      { heading: "Finance analytics", body: "See monthly revenue and inflow trends across payments, fees and donations." },
    ],
  },
  {
    id: "calendar",
    title: "Monitor & Calendar",
    icon: LayoutDashboard,
    color: "bg-cyan-800",
    audience: "National Admin",
    summary: "National submissions monitor and programme calendar.",
    sections: [
      { heading: "Programme calendar", body: "View all submissions grouped by month, detect date clashes by jurisdiction, and reschedule. Use 'Monitor Submissions' from the programme page." },
    ],
  },
];
